名称： 测试构建

在：
# 推：
#枢纽：
＃ - 主要的
# 拉取请求：
  工作流程_调度：

工作：
  建造者：
    运行：ubuntu-latest
    脚步：
      - 使用：actions/checkout@v3
        和：
          获取深度：0
      - 名称：使用 Gradle 构建
        运行： |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      - 名称：准备应用程序
        运行： |
          mkdir -p ${{ github.workspace }}/apk/
          对于 `find ~ -name "*.apk" -print` 中的文件；做
            mv "$file" ${{ github.workspace }}/apk/
          完毕
      - 名称： 上传应用程序到神器
        使用：actions/upload-artifact@v3
        和：
          名称：com.github.tvbox.osc
          路径：${{github.workspace}}/apk/*
